# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Multiple-OS Settings
if [ `uname` = "Linux" ]; then
    # all linux server config
    export ANACONDAPATH=$HOME/app/anaconda3
    export PYTHONPATH=$PYTHONPATH:$ANACONDAPATH/lib/python3.6/site-packages

    case `hostname` in
        "peggy")
            export PATH=$ANACONDAPATH/bin:$PATH
        ;;
        "elmo")
            export JAVA_HOME=/usr/java/jre1.8.0_211
            export PATH=$JAVA_HOME/bin:$ANACONDAPATH/bin:$PATH
        ;;
        "xenial-165")
            export PATH=$ANACONDAPATH/bin:$PATH
        ;;
        "iZbp11i2v86dja5a7kn5apZ")
		;;
    esac
elif [ `uname` = "Darwin" ]; then
    case `hostname` in 
        "YF-MBP.local")
			# mac path
			export PATH=$HOME/.nvm/versions/node/v10.15.3/bin/:/usr/local/Homebrew/bin:$HOME/bin:/usr/local/bin:$PATH
			# mac alias
            alias sshcl="ssh yf@10.214.33.165"
            alias sshzq="ssh yf@192.168.23.51"
            alias sshpeggy="ssh yf@47.103.9.181 -p 6000"
            alias sshelmo="ssh yf@47.103.9.181 -p 6001"
            alias sshkg="ssh yf@120.27.214.45"
			alias lc="leetcode"
			alias lcpick="builtin cd ~/Code/leetcode && leetcode pick -gex"
			alias lctest="leetcode test %"
			alias lcpush="leetcode push %"
        ;;
    esac
fi


# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="agnoster"
# ZSH_THEME="ys"
# ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git z colored-man-pages zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/rsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias h="history"
alias zrc="vim ~/.zshrc"
alias vrc="vim ~/.vimrc"
alias c="clear"
alias vi="vim"
alias l="ls -a"
alias q="logout"
# git alias
alias ga="git add"
alias gaa="git add ."
alias gb="git branch"
alias gc="git commit -am"
alias gd="git diff"
alias glog="git log --oneline --graph"
alias grlog="git reflog"
alias gst="git status -s"
#
function cd(){
    #emulate _LR zsh
    builtin cd $@ &&
    ls
}

function upload(){
    case $2 in 
        "elmo")
            scp -r -P 6001 $1 yf@47.103.9.181:/home/yf/
        ;;
        "peggy")
            scp -r -P 6000 $1 yf@47.103.9.181:/home/yf/
        ;;
        "cl")
            scp -r $1 yf@10.214.33.165:/home/yf/
        ;;
        "kg")
            scp -r $1 yf@120.27.214.45:/home/yf/
        ;;
    esac
}

function download(){
    case $1 in 
        "elmo")
            scp -r -P 6001 yf@47.103.9.181:$2 $3 
        ;;
        "peggy")
            scp -r -P 6000 yf@47.103.9.181:$2 $3 
        ;;
        "cl")
            scp -r yf@10.214.33.165:$2 $3 
        ;;
        "kg")
            scp -r yf@120.27.214.45:$2 $3 
        ;;
    esac
}

prompt_context() {
  if [[ "$USER" != "$DEFAULT_USER" || -n "$SSH_CLIENT" ]]; then
    prompt_segment 202 0 "%(!.%{%F{yellow}%}.)%n@%m"
    # prompt_segment black default "%(!.%{%F{yellow}%}.)%n@%m"
  fi
}
# Status:
# - was there an error
# - am I root
# - are there background jobs?
prompt_status() {
  local -a symbols

  [[ $RETVAL -ne 0 ]] && symbols+="%{%F{black}%}✘"
  [[ $UID -eq 0 ]] && symbols+="%{%F{yellow}%}⚡"
  [[ $(jobs -l | wc -l) -gt 0 ]] && symbols+="%{%F{cyan}%}⚙"

  [[ -n "$symbols" ]] && prompt_segment 196 default "$symbols"
  # [[ -n "$symbols" ]] && prompt_segment white default "$symbols"
}

# Virtualenv: current working virtualenv
prompt_virtualenv() {
  local virtualenv_path="";
  if [[ -n "$CONDA_DEFAULT_ENV" ]]; then
    virtualenv_path="$CONDA_DEFAULT_ENV"
  elif [[ -n "$VIRTUAL_ENV" ]]; then
    virtualenv_path="$VIRTUAL_ENV"
  fi
  if [[ -n $virtualenv_path && -n $VIRTUAL_ENV_DISABLE_PROMPT ]]; then
    prompt_segment blue black "(`basename $virtualenv_path`)"
  fi
}

# redefine prompt_context for hiding user@hostname
build_prompt() {
  RETVAL=$?
  prompt_context
  prompt_dir
  prompt_git
  prompt_virtualenv
  prompt_status
  prompt_bzr
  prompt_hg
  prompt_end
}

set -o emacs

bindkey '^ ' autosuggest-accept

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


# # >>> conda initialize >>>
# # !! Contents within this block are managed by 'conda init' !!
# __conda_setup="$('/Users/yf/anaconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
# if [ $? -eq 0 ]; then
#     eval "$__conda_setup"
# else
#     if [ -f "/Users/yf/anaconda3/etc/profile.d/conda.sh" ]; then
#         . "/Users/yf/anaconda3/etc/profile.d/conda.sh"
#     else
#         export PATH="/Users/yf/anaconda3/bin:$PATH"
#     fi
# fi
# unset __conda_setup
# # <<< conda initialize <<<


